deployment:
  tasks:
    - export DEPLOYPATH=/home/your_user/public_html/
    - /bin/cp -R backend/dist/* $DEPLOYPATH/api/
    - /bin/cp -R frontend/build/* $DEPLOYPATH/
    - /bin/mkdir -p $DEPLOYPATH/logs
    - /bin/chmod 755 $DEPLOYPATH/api/index.js
