#!/bin/bash
# Shunya Sentinel v2.0 - Production Health Monitor & Self-Healer
# Generated by Antigravity

LOG_DIR="/home/gaugyanc/logs"
LOG_FILE="$LOG_DIR/sentinel_monitor.log"
mkdir -p "$LOG_DIR"

timestamp() {
    date "+%Y-%m-%d %H:%M:%S"
}

log() {
    echo "[$1] $(timestamp) - $2"
    echo "[$1] $(timestamp) - $2" >> "$LOG_FILE"
}

log "INFO" "Starting Shunya Sentinel Scan..."

# 1. Directory Structure Integrity Check (The 'Home' Bug)
if [ -d "/home/gaugyanc/gaugyan-api/home" ]; then
    log "CRITICAL" "Nested directory structure detected at /home/gaugyanc/gaugyan-api/home"
    # Auto-fix could go here, but for now we alert
    echo "⚠️  Nested directory detected. Recommendation: Manual cleanup required."
else
    log "PASS" "Directory structure appears correct (flat)."
fi

# 2. API Health Check
API_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://api.gaugyanworld.org/health)
if [ "$API_STATUS" -eq 200 ]; then
    log "PASS" "Backend API is reachable (Status: $API_STATUS)"
else
    log "FAIL" "Backend API unreachable (Status: $API_STATUS)"
fi

# 3. Frontend Availability Check
FRONT_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://gaugyanworld.org)
if [ "$FRONT_STATUS" -eq 200 ]; then
    log "PASS" "Frontend is live (Status: $FRONT_STATUS)"
else
    log "FAIL" "Frontend unreachable (Status: $FRONT_STATUS)"
fi

# 4. Database Connectivity (via internal Node check or API)
# We'll use the API's health endpoint which usually checks DB
DB_CHECK=$(curl -s https://api.gaugyanworld.org/api/health)
if [[ "$DB_CHECK" == *"ok"* ]] || [[ "$DB_CHECK" == *"success"* ]]; then
    log "PASS" "Database connection verified via API"
else
    log "WARN" "Database check inconclusive: $DB_CHECK"
fi

log "INFO" "Sentinel Scan Complete."
echo "----------------------------------------"
tail -n 5 "$LOG_FILE"
