const PERMISSION = require("./permission");

const rolePermission = {
    Admin: [
        PERMISSION.MANAGE_USERS,
        PERMISSION.CREATE_COURSES,
        PERMISSION.DELETE_COURSES,
        PERMISSION.EDIT_COURSES,
        PERMISSION.PUBLISH_NEWS,
        PERMISSION.DELETE_NEWS,
        PERMISSION.EDIT_NEWS,
        PERMISSION.UPLOAD_ART,
        PERMISSION.SELL_ON_MARKETPLACE,
        PERMISSION.ADD_PRODUCT,
        PERMISSION.UPDATE_PRODUCT,
        PERMISSION.DELETE_PRODUCT,
        PERMISSION.MANAGE_INVENTORY,
        PERMISSION.MANAGE_PAYMENTS,
        PERMISSION.MANAGE_PROMO_CODE,
        PERMISSION.UPLOAD_MUSIC,
        PERMISSION.EDIT_MUSIC,
        PERMISSION.DELETE_MUSIC,
        PERMISSION.UPLOAD_PODCAST,
        PERMISSION.EDIT_PODCAST,
        PERMISSION.DELETE_PODCAST,
        PERMISSION.MANAGE_GAUSHALA,
        PERMISSION.VIEW_DONATIONS,
    ],

    Instructor: [
        PERMISSION.CREATE_COURSES,
        PERMISSION.DELETE_COURSES,
        PERMISSION.EDIT_COURSES,
    ],

    Vendor: [
        PERMISSION.SELL_ON_MARKETPLACE,
        PERMISSION.ADD_PRODUCT,
        PERMISSION.UPDATE_PRODUCT,
        PERMISSION.DELETE_PRODUCT,
        PERMISSION.MANAGE_INVENTORY,
        PERMISSION.VIEW_VENDOR_DASHBOARD,
        PERMISSION.VIEW_ORDERS,
        PERMISSION.ACCEPT_ORDERS,
    ],

    Editor: [
        PERMISSION.PUBLISH_NEWS,
        PERMISSION.EDIT_NEWS,
    ],

    Artist: [
        PERMISSION.UPLOAD_ART,
        PERMISSION.SELL_ON_MARKETPLACE,
        PERMISSION.UPLOAD_MUSIC,
        PERMISSION.EDIT_MUSIC,
        PERMISSION.UPLOAD_PODCAST,
        PERMISSION.EDIT_PODCAST,
    ],

    GaushalaOwner: [
        PERMISSION.MANAGE_GAUSHALA,
        PERMISSION.VIEW_DONATIONS,
    ],

    Learner: [
        PERMISSION.ENROLL_COURSES,
    ],
};

module.exports = rolePermission;
